name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build the project
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
- name: Set up JDK 8
  uses: actions/setup-java@v3
  with:
    java-version: '8'
    distribution: 'temurin'


      - name: Build the Application
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test
